-- Initial schema for Hookwing
-- Generated by S-1: Drizzle ORM setup + schema definitions
-- Database: Cloudflare D1 (SQLite-compatible)

-- ============================================================================
-- Workspaces - tenant/org accounts
-- ============================================================================

CREATE TABLE IF NOT EXISTS workspaces (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  tier_slug TEXT NOT NULL DEFAULT 'paper-plane',
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

-- ============================================================================
-- API Keys - authentication keys per workspace
-- ============================================================================

CREATE TABLE IF NOT EXISTS api_keys (
  id TEXT PRIMARY KEY NOT NULL,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL,
  key_prefix TEXT NOT NULL,
  scopes TEXT,
  last_used_at INTEGER,
  expires_at INTEGER,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS api_keys_workspace_id_idx ON api_keys(workspace_id);
CREATE INDEX IF NOT EXISTS api_keys_key_prefix_idx ON api_keys(key_prefix);

-- ============================================================================
-- Endpoints - webhook destinations
-- ============================================================================

CREATE TABLE IF NOT EXISTS endpoints (
  id TEXT PRIMARY KEY NOT NULL,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  description TEXT,
  secret TEXT NOT NULL,
  event_types TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  rate_limit_per_second INTEGER,
  metadata TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS endpoints_workspace_id_idx ON endpoints(workspace_id);

-- ============================================================================
-- Events - incoming webhook events
-- ============================================================================

CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY NOT NULL,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  payload TEXT NOT NULL,
  headers TEXT,
  source_ip TEXT,
  received_at INTEGER NOT NULL,
  processed_at INTEGER,
  status TEXT NOT NULL DEFAULT 'pending'
);

CREATE INDEX IF NOT EXISTS events_workspace_received_at_idx ON events(workspace_id, received_at);
CREATE INDEX IF NOT EXISTS events_workspace_status_idx ON events(workspace_id, status);

-- ============================================================================
-- Deliveries - delivery attempts per event per endpoint
-- ============================================================================

CREATE TABLE IF NOT EXISTS deliveries (
  id TEXT PRIMARY KEY NOT NULL,
  event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  endpoint_id TEXT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  attempt_number INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'pending',
  response_status_code INTEGER,
  response_body TEXT,
  response_headers TEXT,
  error_message TEXT,
  duration_ms INTEGER,
  next_retry_at INTEGER,
  delivered_at INTEGER,
  created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS deliveries_event_id_idx ON deliveries(event_id);
CREATE INDEX IF NOT EXISTS deliveries_endpoint_id_idx ON deliveries(endpoint_id);
CREATE INDEX IF NOT EXISTS deliveries_workspace_created_at_idx ON deliveries(workspace_id, created_at);
CREATE INDEX IF NOT EXISTS deliveries_status_next_retry_at_idx ON deliveries(status, next_retry_at);

-- ============================================================================
-- Usage Daily - daily usage tracking for billing/limits
-- ============================================================================

CREATE TABLE IF NOT EXISTS usage_daily (
  id TEXT PRIMARY KEY NOT NULL,
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  events_received INTEGER NOT NULL DEFAULT 0,
  deliveries_attempted INTEGER NOT NULL DEFAULT 0,
  deliveries_succeeded INTEGER NOT NULL DEFAULT 0,
  deliveries_failed INTEGER NOT NULL DEFAULT 0,
  UNIQUE (workspace_id, date)
);

CREATE UNIQUE INDEX IF NOT EXISTS usage_daily_workspace_date_idx ON usage_daily(workspace_id, date);
