/**
 * build-tokens.mjs
 * Generates styles/tokens.css from design/tokens/hookwing.tokens.json
 * Run: node scripts/build-tokens.mjs
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..'); // monorepo root (website/scripts → hookwing/)
const TOKENS_JSON = resolve(ROOT, 'design/tokens/hookwing.tokens.json');
const OUTPUT_CSS  = resolve(__dirname, '../styles/tokens.css');

const tokens = JSON.parse(readFileSync(TOKENS_JSON, 'utf8'));
const { primitive, semantic, dark, typography, spacing, radius, shadow, motion, layout, dataViz } = tokens;

const p = primitive;
const sp = spacing;
const mo = motion;

const css = `/* =============================================================
   tokens.css — GENERATED by scripts/build-tokens.mjs
   Source: design/tokens/hookwing.tokens.json
   DO NOT EDIT DIRECTLY — run: node scripts/build-tokens.mjs
   Last built: ${new Date().toISOString()}
============================================================== */

:root {
  /* ── Color Primitives ─────────────────────────────────────── */

  /* Blue */
  --primitive-blue-950: ${p.blue['950'].$value};
  --primitive-blue-900: ${p.blue['900'].$value};
  --primitive-blue-800: ${p.blue['800'].$value};
  --primitive-blue-700: ${p.blue['700'].$value};
  --primitive-blue-100: ${p.blue['100'].$value};
  --primitive-blue-50:  ${p.blue['50'].$value};

  /* Green */
  --primitive-green-700: ${p.green['700'].$value};
  --primitive-green-600: ${p.green['600'].$value};
  --primitive-green-500: ${p.green['500'].$value};
  --primitive-green-100: ${p.green['100'].$value};
  --primitive-green-50:  ${p.green['50'].$value};

  /* Yellow/Amber */
  --primitive-yellow-600: ${p.yellow['600'].$value};
  --primitive-yellow-500: ${p.yellow['500'].$value};
  --primitive-yellow-400: ${p.yellow['400'].$value};
  --primitive-yellow-100: ${p.yellow['100'].$value};
  --primitive-yellow-50:  ${p.yellow['50'].$value};

  /* Neutral */
  --primitive-neutral-950: ${p.neutral['950'].$value};
  --primitive-neutral-800: ${p.neutral['800'].$value};
  --primitive-neutral-700: ${p.neutral['700'].$value};
  --primitive-neutral-400: ${p.neutral['400'].$value};
  --primitive-neutral-200: ${p.neutral['200'].$value};
  --primitive-neutral-100: ${p.neutral['100'].$value};
  --primitive-neutral-50:  ${p.neutral['50'].$value};
  --primitive-white:       ${p.neutral.white.$value};

  /* Red */
  --primitive-red-600: ${p.red['600'].$value};
  --primitive-red-100: ${p.red['100'].$value};

  /* ── Semantic Colors (Light Mode) ─────────────────────────── */
  --color-bg:              var(--primitive-neutral-50);
  --color-surface:         var(--primitive-white);
  --color-surface-raised:  var(--primitive-neutral-100);
  --color-surface-overlay: rgba(0,42,58,.04);

  --color-ink-strong:   var(--primitive-neutral-950);
  --color-ink-base:     var(--primitive-neutral-800);
  --color-ink-muted:    var(--primitive-neutral-700);
  --color-ink-disabled: var(--primitive-neutral-400);
  --color-ink-inverse:  var(--primitive-white);

  --color-brand-primary:      var(--primitive-blue-900);
  --color-brand-secondary:    var(--primitive-blue-800);
  --color-brand-action:       var(--primitive-green-600);
  --color-brand-action-hover: var(--primitive-green-700);
  --color-brand-signal:       var(--primitive-yellow-500);

  --color-border:        var(--primitive-neutral-200);
  --color-border-strong: var(--primitive-neutral-400);
  --color-border-brand:  var(--primitive-green-600);

  --color-focus:         #86B7FE;
  --color-hover-overlay: rgba(0,42,58,.05);

  --color-success:    var(--primitive-green-600);
  --color-success-bg: var(--primitive-green-50);
  --color-warning:    var(--primitive-yellow-500);
  --color-warning-bg: var(--primitive-yellow-50);
  --color-error:      var(--primitive-red-600);
  --color-error-bg:   var(--primitive-red-100);

  /* ── Data Visualization Palette ───────────────────────────── */
  --color-viz-1: ${dataViz['1'].$value}; /* ${dataViz['1'].$description} */
  --color-viz-2: ${dataViz['2'].$value}; /* ${dataViz['2'].$description} */
  --color-viz-3: ${dataViz['3'].$value}; /* ${dataViz['3'].$description} */
  --color-viz-4: ${dataViz['4'].$value}; /* ${dataViz['4'].$description} */
  --color-viz-5: ${dataViz['5'].$value}; /* ${dataViz['5'].$description} */
  --color-viz-6: ${dataViz['6'].$value}; /* ${dataViz['6'].$description} */
  --color-viz-7: ${dataViz['7'].$value}; /* ${dataViz['7'].$description} */

  /* ── Typography ───────────────────────────────────────────── */
  --font-display: ${typography['font-display'].$value};
  --font-body:    ${typography['font-body'].$value};
  --font-mono:    ${typography['font-mono'].$value};

  /* Type scale */
  --text-display-size:   ${typography.scale.display.size.$value};
  --text-display-lh:     ${typography.scale.display.lineHeight.$value};
  --text-h1-size:        ${typography.scale.h1.size.$value};
  --text-h1-lh:          ${typography.scale.h1.lineHeight.$value};
  --text-h2-size:        ${typography.scale.h2.size.$value};
  --text-h2-lh:          ${typography.scale.h2.lineHeight.$value};
  --text-h3-size:        ${typography.scale.h3.size.$value};
  --text-h3-lh:          ${typography.scale.h3.lineHeight.$value};
  --text-h4-size:        ${typography.scale.h4.size.$value};
  --text-h4-lh:          ${typography.scale.h4.lineHeight.$value};
  --text-h5-size:        ${typography.scale.h5.size.$value};
  --text-h5-lh:          ${typography.scale.h5.lineHeight.$value};
  --text-body-size:      ${typography.scale.body.size.$value};
  --text-body-lh:        ${typography.scale.body.lineHeight.$value};
  --text-small-size:     ${typography.scale.small.size.$value};
  --text-small-lh:       ${typography.scale.small.lineHeight.$value};
  --text-label-size:     ${typography.scale.label.size.$value};
  --text-label-lh:       ${typography.scale.label.lineHeight.$value};
  --text-code-size:      ${typography.scale.code.size.$value};
  --text-code-lh:        ${typography.scale.code.lineHeight.$value};

  /* ── Spacing (8-pt grid) ──────────────────────────────────── */
  --space-1:  ${sp['1'].$value};
  --space-2:  ${sp['2'].$value};
  --space-3:  ${sp['3'].$value};
  --space-4:  ${sp['4'].$value};
  --space-5:  ${sp['5'].$value};
  --space-6:  ${sp['6'].$value};
  --space-7:  ${sp['7'].$value};
  --space-8:  ${sp['8'].$value};
  --space-9:  ${sp['9'].$value};
  --space-10: ${sp['10'].$value};
  --space-11: ${sp['11'].$value};
  --space-12: ${sp['12'].$value};

  /* Named spacing aliases (semantic intent) */
  --space-hair:        var(--space-1);  /* 4px  — micro, borders */
  --space-tight:       var(--space-2);  /* 8px  — icon gaps */
  --space-snug:        var(--space-3);  /* 12px — compact padding */
  --space-comfortable: var(--space-4);  /* 16px — default padding */
  --space-roomy:       var(--space-5);  /* 24px — card padding */
  --space-open:        var(--space-6);  /* 32px — section spacing */
  --space-spacious:    var(--space-8);  /* 48px — feature sections */
  --space-airy:        var(--space-9);  /* 64px — hero sections */

  /* ── Border Radius ────────────────────────────────────────── */
  --radius-xs:   ${radius.xs.$value};
  --radius-sm:   ${radius.sm.$value};
  --radius-md:   ${radius.md.$value};
  --radius-lg:   ${radius.lg.$value};
  --radius-xl:   ${radius.xl.$value};
  --radius-full: ${radius.full.$value};

  /* ── Shadows / Elevation ──────────────────────────────────── */
  --shadow-sm:    ${shadow.sm.$value};
  --shadow-md:    ${shadow.md.$value};
  --shadow-lg:    ${shadow.lg.$value};
  --shadow-xl:    ${shadow.xl.$value};
  --shadow-focus: ${shadow.focus.$value};
  --shadow-brand: ${shadow.brand.$value};

  /* ── Motion ───────────────────────────────────────────────── */
  --dur-instant: ${mo.duration.instant.$value};
  --dur-fast:    ${mo.duration.fast.$value};
  --dur-base:    ${mo.duration.base.$value};
  --dur-slow:    ${mo.duration.slow.$value};
  --ease:        ${mo.easing.default.$value};
  --ease-decel:  ${mo.easing.decel.$value};
  --ease-spring: ${mo.easing.spring.$value};

  /* ── Layout ───────────────────────────────────────────────── */
  --container-sm: ${layout['container-sm'].$value};
  --container-md: ${layout['container-md'].$value};
  --container-lg: ${layout['container-lg'].$value};
  --container-xl: ${layout['container-xl'].$value};
  --nav-height:   ${layout['nav-height'].$value};
}

/* ── Dark Mode Token Overrides ──────────────────────────────── */
[data-theme="dark"] {
  --color-bg:              var(--primitive-blue-950);
  --color-surface:         var(--primitive-blue-900);
  --color-surface-raised:  var(--primitive-blue-800);
  --color-surface-overlay: rgba(255,255,255,.04);

  --color-ink-strong:   var(--primitive-white);
  --color-ink-base:     #CBD5E1;
  --color-ink-muted:    var(--primitive-neutral-400);
  --color-ink-disabled: #475569;
  --color-ink-inverse:  var(--primitive-neutral-950);

  --color-brand-primary:      var(--primitive-green-500);
  --color-brand-secondary:    var(--primitive-green-600);
  --color-brand-action:       var(--primitive-green-500);
  --color-brand-action-hover: var(--primitive-green-600);
  --color-brand-signal:       var(--primitive-yellow-400);

  --color-border:        rgba(255,255,255,.10);
  --color-border-strong: rgba(255,255,255,.20);
  --color-border-brand:  var(--primitive-green-500);

  --color-hover-overlay: rgba(255,255,255,.06);

  --color-success:    var(--primitive-green-500);
  --color-success-bg: rgba(0,157,100,.12);
  --color-warning:    var(--primitive-yellow-400);
  --color-warning-bg: rgba(255,193,7,.10);
  --color-error:      #F87171;
  --color-error-bg:   rgba(220,38,38,.12);
}

/* ── Reduced Motion ─────────────────────────────────────────── */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
  }
}
`;

writeFileSync(OUTPUT_CSS, css, 'utf8');
console.log(`✅ tokens.css generated → ${OUTPUT_CSS}`);
console.log(`   Source: ${TOKENS_JSON}`);
