#!/usr/bin/env node

/**
 * CLI for @hookwing/agent-skills
 *
 * Usage:
 *   npx @hookwing/agent-skills init stripe
 *   npx @hookwing/agent-skills init github
 *   npx @hookwing/agent-skills list
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface CliArgs {
  command: string;
  integration?: string;
  outputDir?: string;
}

/**
 * Parse CLI arguments
 */
function parseArgs(): CliArgs {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    printHelp();
    process.exit(0);
  }

  const command = args[0];

  if (command === 'help' || command === '--help' || command === '-h') {
    printHelp();
    process.exit(0);
  }

  if (command === 'list' || command === 'ls') {
    return { command: 'list' };
  }

  if (command === 'init') {
    const integration = args[1];
    const outputDir = args[2] || '.';

    if (!integration) {
      console.error('Error: integration name required');
      console.error('Usage: npx @hookwing/agent-skills init <integration> [output-dir]');
      console.error('Example: npx @hookwing/agent-skills init stripe ./webhooks');
      process.exit(1);
    }

    return { command: 'init', integration, outputDir };
  }

  console.error(`Unknown command: ${command}`);
  printHelp();
  process.exit(1);
}

/**
 * Print help message
 */
function printHelp() {
  console.log(`
@hookwing/agent-skills CLI

Usage:
  npx @hookwing/agent-skills init <integration> [output-dir]
  npx @hookwing/agent-skills list

Commands:
  init <integration>    Scaffold a webhook handler for the integration
  list                 List available integrations

Examples:
  npx @hookwing/agent-skills init stripe           # Create stripe handler in current dir
  npx @hookwing/agent-skills init github ./src     # Create github handler in ./src

Available Integrations:
  stripe   - Stripe payment webhooks
  github   - GitHub repository webhooks
`);
}

/**
 * Get integration template
 */
function getTemplate(integration: string): { filename: string; content: string } | null {
  const templates: Record<string, { filename: string; content: string }> = {
    stripe: {
      filename: 'stripe-handler.ts',
      content: `/**
 * Stripe webhook handler
 * Generated by @hookwing/agent-skills
 *
 * Setup:
 * 1. Add webhook URL in Stripe Dashboard: https://your-domain.com/webhooks/stripe
 * 2. Set STRIPE_WEBHOOK_SECRET in your environment
 * 3. Configure signature tolerance if needed (default: 300s)
 */

import { createStripeHandler } from '@hookwing/agent-skills/stripe';

const handler = createStripeHandler({
  signingSecret: process.env.STRIPE_WEBHOOK_SECRET!,
  toleranceSeconds: 300, // 5 minutes
});

export default handler;

// Example: Export specific handlers
/*
export async function handleStripeWebhook(req: Request): Promise<Response> {
  const signatureHeader = req.headers.get('Stripe-Signature');
  const payload = await req.text();

  const event = handler.verify(payload, signatureHeader!);

  await handler.handle(event, {
    'payment_intent.succeeded': async (evt) => {
      // Handle successful payment
      console.log('Payment succeeded:', evt.data.object);
    },

    'payment_intent.payment_failed': async (evt) => {
      // Handle failed payment
      console.log('Payment failed:', evt.data.object);
    },

    'customer.subscription.created': async (evt) => {
      // Handle new subscription
      console.log('New subscription:', evt.data.object);
    },

    'customer.subscription.deleted': async (evt) => {
      // Handle cancelled subscription
      console.log('Subscription cancelled:', evt.data.object);
    },

    'invoice.paid': async (evt) => {
      // Handle paid invoice
      console.log('Invoice paid:', evt.data.object);
    },

    'invoice.payment_failed': async (evt) => {
      // Handle failed invoice payment
      console.log('Invoice payment failed:', evt.data.object);
    },
  });

  return new Response(JSON.stringify({ received: true }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
}
*/
`,
    },
    github: {
      filename: 'github-handler.ts',
      content: `/**
 * GitHub webhook handler
 * Generated by @hookwing/agent-skills
 *
 * Setup:
 * 1. Go to Repo Settings → Webhooks
 * 2. Add webhook URL: https://your-domain.com/webhooks/github
 * 3. Set GITHUB_WEBHOOK_SECRET in your environment
 * 4. Select events to receive
 */

import { createGitHubHandler } from '@hookwing/agent-skills/github';

const handler = createGitHubHandler({
  webhookSecret: process.env.GITHUB_WEBHOOK_SECRET!,
});

export default handler;

// Example: Export specific handlers
/*
export async function handleGitHubWebhook(req: Request): Promise<Response> {
  const signatureHeader = req.headers.get('X-Hub-Signature-256');
  const eventType = req.headers.get('X-GitHub-Event');
  const payload = await req.text();

  const event = handler.verify(payload, signatureHeader!);

  await handler.handle(eventType!, event, {
    'push': async (evt) => {
      // Handle push event
      console.log('Push to:', evt.ref);
      console.log('Commits:', evt.commits?.length);
    },

    'pull_request': async (evt) => {
      // Handle pull request
      console.log('PR action:', evt.action);
      console.log('PR number:', evt.number);
    },

    'issues': async (evt) => {
      // Handle issues
      console.log('Issue action:', evt.action);
      console.log('Issue:', evt.issue?.title);
    },

    'release': async (evt) => {
      // Handle releases
      console.log('Release action:', evt.action);
      console.log('Tag:', evt.release?.tag_name);
    },

    'workflow_dispatch': async (evt) => {
      // Handle manual workflow triggers
      console.log('Workflow:', evt.workflow);
    },
  });

  return new Response(JSON.stringify({ received: true }), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
}
*/
`,
    },
  };

  return templates[integration.toLowerCase()] || null;
}

/**
 * List available integrations
 */
function listIntegrations() {
  console.log('Available integrations:\n');
  console.log('  stripe   - Stripe payment webhooks');
  console.log('  github   - GitHub repository webhooks');
  console.log('\nMore integrations coming soon: shopify, slack, twilio, sendgrid');
}

/**
 * Initialize an integration
 */
function initIntegration(integration: string, outputDir: string) {
  const template = getTemplate(integration);

  if (!template) {
    console.error(`Error: Unknown integration "${integration}"`);
    console.error('Run "npx @hookwing/agent-skills list" to see available integrations');
    process.exit(1);
  }

  const outputPath = join(outputDir, template.filename);

  // Check if file already exists
  if (existsSync(outputPath)) {
    console.error(`Error: File already exists: ${outputPath}`);
    console.error('Use --force to overwrite');
    process.exit(1);
  }

  // Create output directory if needed
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  writeFileSync(outputPath, template.content);

  console.log(`Created ${template.filename} in ${outputDir}/`);
  console.log('\nNext steps:');
  console.log('1. Set up your webhook secret in environment variables');
  console.log('2. Import and use the handler in your app');
  console.log(`3. Deploy and configure the webhook URL in ${integration} dashboard`);
}

/**
 * Main CLI entry point
 */
function main() {
  const args = parseArgs();

  switch (args.command) {
    case 'list':
      listIntegrations();
      break;

    case 'init':
      if (!args.integration || !args.outputDir) {
        console.error('Error: integration and output-dir required');
        process.exit(1);
      }
      initIntegration(args.integration, args.outputDir);
      break;

    default:
      printHelp();
  }
}

main();
